import * as fs from 'fs';
import * as path from 'path';

const PROJECTS_BASE_PATH = path.join(process.cwd(), 'generated-projects');

export function ensureProjectDir(projectId: string): string {
  const projectPath = path.join(PROJECTS_BASE_PATH, projectId);
  if (!fs.existsSync(projectPath)) {
    fs.mkdirSync(projectPath, { recursive: true });
  }
  return projectPath;
}

export function writeProjectFile(projectId: string, filePath: string, content: string): string {
  const projectPath = ensureProjectDir(projectId);
  const fullPath = path.join(projectPath, filePath);

  const dirPath = path.dirname(fullPath);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  fs.writeFileSync(fullPath, content, 'utf-8');
  return fullPath;
}

export function readProjectFile(projectId: string, filePath: string): string | null {
  const projectPath = path.join(PROJECTS_BASE_PATH, projectId);
  const fullPath = path.join(projectPath, filePath);

  if (fs.existsSync(fullPath)) {
    return fs.readFileSync(fullPath, 'utf-8');
  }
  return null;
}

export function listProjectFiles(projectId: string, subPath?: string): string[] {
  const projectPath = path.join(PROJECTS_BASE_PATH, projectId);
  const targetPath = subPath ? path.join(projectPath, subPath) : projectPath;

  if (!fs.existsSync(targetPath)) {
    return [];
  }

  const files: string[] = [];

  function traverse(dir: string, relativePath: string = '') {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const entryRelativePath = relativePath ? path.join(relativePath, entry.name) : entry.name;
      if (entry.isDirectory()) {
        traverse(path.join(dir, entry.name), entryRelativePath);
      } else {
        files.push(entryRelativePath);
      }
    }
  }

  traverse(targetPath);
  return files;
}

export function extractCodeBlock(content: string): string {
  const codeBlockMatch = content.match(/```[\w]*\n([\s\S]*?)\n```/);
  if (codeBlockMatch) {
    return codeBlockMatch[1].trim();
  }

  const justCode = content.replace(/^[\s\S]*?```[\w]*\n/, '').replace(/```[\s\S]*$/, '').trim();
  if (justCode.length > 0) {
    return justCode;
  }

  return content.trim();
}

export function generateProjectStructure(projectId: string, projectType: 'nextjs' | 'express' | 'fullstack') {
  const projectPath = ensureProjectDir(projectId);

  writeProjectFile(projectId, 'package.json', JSON.stringify({
    name: `opc-project-${projectId}`,
    version: '0.1.0',
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start'
    },
    dependencies: {
      next: '14.0.0',
      react: '18.2.0',
      'react-dom': '18.2.0'
    },
    devDependencies: {
      '@types/node': '20.9.0',
      '@types/react': '18.2.37',
      'typescript': '5.2.2'
    }
  }, null, 2));

  writeProjectFile(projectId, 'tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] }
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules']
  }, null, 2));

  writeProjectFile(projectId, 'next.config.js', `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
`);

  writeProjectFile(projectId, 'app/layout.tsx', `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'OPC Generated App',
  description: 'Generated by OPC Agent System',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  );
}
`);

  writeProjectFile(projectId, 'app/globals.css', `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: system-ui, -apple-system, sans-serif;
}
`);

  writeProjectFile(projectId, 'tailwind.config.js', `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`);

  writeProjectFile(projectId, 'postcss.config.js', `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`);

  const pkgPath = path.join(projectPath, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  pkg.devDependencies.tailwindcss = '^3.3.5';
  pkg.devDependencies.autoprefixer = '^10.4.16';
  pkg.devDependencies.postcss = '^8.4.31';
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

  return projectPath;
}
